### PR TITLE
Makefile: disable NODEJS_CATCH_EXIT

### PR DESCRIPTION
**Pull request by jakogut**
Emscripten by default catches and handles exit(), which results in a
dump of the module, and necessitates a lot of scrolling to see the
actual Node error and relevant backtrace.

Since node-ext2fs is a library, disable this global error handler in
favor of letting the application do it.

See also:
https://github.com/emscripten-core/emscripten/blob/1.38.37/src/settings.js#L517-L524
https://github.com/kripken/sql.js/commit/b3d2c37f05bf60457025b3e04994f5a253f5092e

Change-type: patch
Signed-off-by: Joseph Kogut <joseph@balena.io>

### CODE REVIEW

**Comment by zwhitchcox** [comment]
@jakogut Do we want to add `NODEJS_CATCH_REJECTION=0` too?

**Comment by ab77** [comment]
@jakogut is this PR still relevant?

**Comment by jakogut** [comment]
@ab77 As far as I know, the problem still remains, though I'm not 100% on this solving it.

**Comment by ab77** [comment]
Closing for now: https://github.com/balena-io-modules/node-ext2fs/pull/101#issuecomment-1372917752

**Pull request closed without merging**
